name: static code test
on: [push]
jobs:
  lint:
    name: Analyze code
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-go@v1
        with:
          go-version: 1.12.9
      - name: Prepare
        run: make setup
      - name: golangci-lint run
        run: bin/golangci-lint run
  test:
    name: Run test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-go@v1
        with:
          go-version: 1.12.9
      - name: Prepare
        run: |
          go mod download
          go mod tidy
      - name: go test
        run: make test
